#cloud-config
# Cloud-init configuration for System Monitor deployment
# This script sets up the System Monitor on a fresh cloud instance

# Update package database on first boot
package_update: true
package_upgrade: true

# Install required system packages
packages:
  - python3
  - python3-pip
  - python3-venv
  - git
  - curl
  - build-essential
  - python3-dev

# Create system user for running the service
users:
  - name: sysmonitor
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

# Run commands on first boot
runcmd:
  - |
    curl -fsSL https://raw.githubusercontent.com/SLYD-Main/SystemMonitor/master/bootstrap.sh | bash -s -- --non-interactive --enable-history

# Optional: Install NVIDIA drivers for GPU support
# Modify the runcmd above to include: --install-gpu-drivers

final_message: |
  ========================================
  System Monitor Installation Complete!
  ========================================

  API Server: http://localhost:8000
  API Docs: http://localhost:8000/docs

  Service Status:
    sudo systemctl status system-monitor

  View Logs:
    sudo journalctl -u system-monitor -f

  CLI Commands:
    cd /opt/SystemMonitor
    source venv/bin/activate
    python main.py --help

  Configuration:
    /opt/SystemMonitor/config.yaml

  For GPU support, uncomment NVIDIA driver
  installation in cloud-init.yaml and reboot.

  ========================================
